#!/bin/sh
cd /boot/home/projects/ports/FreeVerse
package create -b freeverse_0.3-8_gcc2.hpkg
sleep 0.5
package add freeverse_0.3-8_gcc2.hpkg data apps bin
sleep 0.5
addattr BeShare:Info "A simple notepad for entering Appointments, To-dos and Diary entries." freeverse_0.3-8_gcc2.hpkg
becopy freeverse_0.3-8_gcc2.hpkg "/Storage/Haiku/My ports"
mv freeverse_0.3-8_gcc2.hpkg /boot/home/projects/repo

sync
